### ISSUE TITLE
questions about util_funcs.py

### ISSUE THREAD

**Issue by Chuan1997** [Andy-Border/NSHE#1]
I don't understand the 37682 in load_relations(in_path, dataset="dblp", node_cnt=37682), could you please give some explannation?

**Comment by AndyJZhao** [comment]
Hi, thank you for your interest in our work, the node_cnt attribute stands for the total number of nodes in a HIN. You can simply ignore the 37682 value and assign the value that is appropriate for your dataset.

**Comment by Chuan1997** [comment]
So the node_cnt attribute should be set to 11576 if I try to use the DBLP dataset?
Another question is how can I get "_feat.csv" in **load_features()** function

**Comment by AndyJZhao** [comment]
Hi, regarding your questions:
- Yes, it should be  11576 for dblp.
- We did not use any true features in the experiments. The code will run fine without the true features. However, if you have to run NSHE on your own HIN with features, this function might be useful.
