### ISSUE TITLE
relations.txt

### ISSUE THREAD

**Issue by kanhuimin** [Andy-Border/NSHE#2]
Hello, your work is very useful to me. I'd like to ask you about it relations.txt What does each column of the document mean? Especially the last two columns of 0 and 1, looking forward to your reply!

**Comment by AndyJZhao** [comment]
Hi, the first two columns describe the node id of an edge/relation, the third column stands for the relation type defined in relation2id.txt,  the fourth column stands for the edge weight.

**Comment by kanhuimin** [comment]
Thank you very much for your reply. I will try again according to your data format.

**Comment by AndyJZhao** [comment]
Good luck and have fun reseraching : )
