### ISSUE TITLE
question

### ISSUE THREAD

**Issue by alencn1024** [Andy-Border/NSHE#6]
您好！
    看名字应该是中国人，我想咨询一下，在你们的论文中，关于 schema instance 的个数 |S| 是设置的为多少呢，感觉看了一下在论文和源码中都没有找到，抱歉打扰
祝好

**Comment by AndyJZhao** [comment]
有关sample 的具体过程可以在sampler.py 中的gen_ns_instances函数找到。每个 epoch 中，我们 sample 的 ns_instance个数为target type（即有 label 的 type，例如 ACM 中的 P类型） 的节点数。
